name: CI Pipeline

on: push

jobs:
  # Code-Quality:
  #   runs-on: ubuntu-latest
  
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v3
      
  #     - name: setup python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
        
  #     - name: Cache pip dependescies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pip-
      
  #     - name: update pip
  #       run: |
  #         pip install --upgrade pip
      
  #     - name: Check Formatting
  #       run: |
  #         pip install black
  #         black src/ --check --diff
  #         black tests/ --check --diff
  
  CI-CD:

    # needs: Code-Quality  

    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: update pip 
        run: |
          pip install --upgrade pip

      - name: install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: run DVC Pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro 
      
      - name: run model tests
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py
      
      - name: promote model
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python src/registry/promote_model.py
      
      - name: run FastAPI tests
        env:
          ACCESS_TOKEN_EXPIRY_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRY_MINUTES }}
          ALGORITHM : ${{ secrets.ALGORITHM }}
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{  secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          REGION_NAME: ${{ secrets.REGION_NAME }}
          SECRET_KEY : ${{ secrets.SECRET_KEY }}
        run: |
          python -m unittest tests/test_fastapi.py

